package it.unibo.db.unibo;
// Generated 6-set-2018 18.31.48 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Credenziali generated by hbm2java
 */
@Entity
(name="unibo_credenziali")@Table(name="credenziali"
    ,catalog="unibodb"
    , uniqueConstraints = {@UniqueConstraint(columnNames="idUtente"), @UniqueConstraint(columnNames="username")} 
)
public class Credenziali  implements java.io.Serializable {


     private Integer idCredenziale;
     private Utente utente;
     private String username;
     private String password;

    public Credenziali() {
    }

    public Credenziali(Utente utente, String username, String password) {
       this.utente = utente;
       this.username = username;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCredenziale", unique=true, nullable=false)
    public Integer getIdCredenziale() {
        return this.idCredenziale;
    }
    
    public void setIdCredenziale(Integer idCredenziale) {
        this.idCredenziale = idCredenziale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUtente", unique=true, nullable=false)
    public Utente getUtente() {
        return this.utente;
    }
    
    public void setUtente(Utente utente) {
        this.utente = utente;
    }

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


