package it.unibo.db.unibo;
// Generated 6-set-2018 18.31.48 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Utente generated by hbm2java
 */
@Entity
(name="unibo_utente")@Table(name="utente"
    ,catalog="unibodb"
    , uniqueConstraints = @UniqueConstraint(columnNames="codiceFiscale") 
)
public class Utente  implements java.io.Serializable {


     private Integer idUtente;
     private String nome;
     private String cognome;
     private String codiceFiscale;
     private Set<Credenziali> credenzialis = new HashSet<Credenziali>(0);

    public Utente() {
    }

	
    public Utente(String nome, String cognome, String codiceFiscale) {
        this.nome = nome;
        this.cognome = cognome;
        this.codiceFiscale = codiceFiscale;
    }
    public Utente(String nome, String cognome, String codiceFiscale, Set<Credenziali> credenzialis) {
       this.nome = nome;
       this.cognome = cognome;
       this.codiceFiscale = codiceFiscale;
       this.credenzialis = credenzialis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUtente", unique=true, nullable=false)
    public Integer getIdUtente() {
        return this.idUtente;
    }
    
    public void setIdUtente(Integer idUtente) {
        this.idUtente = idUtente;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cognome", nullable=false, length=50)
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    
    @Column(name="codiceFiscale", unique=true, nullable=false, length=50)
    public String getCodiceFiscale() {
        return this.codiceFiscale;
    }
    
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utente")
    public Set<Credenziali> getCredenzialis() {
        return this.credenzialis;
    }
    
    public void setCredenzialis(Set<Credenziali> credenzialis) {
        this.credenzialis = credenzialis;
    }




}


